name:          Ghidul de coding de @mdo
description:   Standarde pentru dezvoltarea unui cod HTML și CSS flexibil și durabil
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
